trigger:
  branches:
    include:
      - main  # Configura el pipeline para que se active en el branch principal

pool:
  vmImage: 'ubuntu-latest'  # Puedes cambiar la imagen según tus necesidades

steps:
  - checkout: self  # Realiza el checkout del repositorio de GitHub
  - script: |
      echo "Sincronizando cambios desde GitHub"
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'GitHubSync'
      publishLocation: 'Container'
